/*
 * dac.c
 *
 *  Created on: Nov 17, 2022
 *      Author: dayton.flores
 */

#include "board.h"
#include "dac.h"

/**
 * \def		PCR_MUX_SEL_DAC
 * \brief	PCR is a 32-bit register where bits 8:10 are a MUX field
 * \detail
 * 		000: Pin disabled (analog)
 * 		001: GPIO
 * 		010: Alternative (see Chapter 2 of Alexander G Dean's Embedded Systems Fundamentals with
 * 			 ARM Cortex-M Based Microcontrollers: Embedded Systems)
 * 		011: TPM2_CH0
 * 		100: Alternative (see Chapter 2 of Alexander G Dean's Embedded Systems Fundamentals with
 * 			 ARM Cortex-M Based Microcontrollers: Embedded Systems)
 * 		101: Alternative (see Chapter 2 of Alexander G Dean's Embedded Systems Fundamentals with
 * 			 ARM Cortex-M Based Microcontrollers: Embedded Systems)
 * 		110: Alternative (see Chapter 2 of Alexander G Dean's Embedded Systems Fundamentals with
 * 			 ARM Cortex-M Based Microcontrollers: Embedded Systems)
 * 		111: Alternative (see Chapter 2 of Alexander G Dean's Embedded Systems Fundamentals with
 * 			 ARM Cortex-M Based Microcontrollers: Embedded Systems)
 */
#define PCR_MUX_SEL_DAC\
	(0)

/**
 * \def		PORTE_DAC0_POS
 * \brief	DAC0 Analog output is located at PTE30
 */
#define PORTE_DAC0_POS\
	(30)

/**
 * \def		C0_DACEN
 * \brief	C0[7] which is DAC Enable
 * \detail
 * 		0: DAC is disabled
 * 		1: DAC is enabled
 */
#define C0_DACEN\
	(1)

/**
 * \def		C0_DACRFS
 * \brief	C0[6] which is DAC Reference Select
 * \detail
 * 		0: Select DACREF_1 as ref voltage
 * 		1: Select DACREF_2 as ref voltage
 */
#define C0_DACRFS\
	(1)

/**
 * \def		C1_DMAEN
 * \brief	C1[7] which is DMA Enable Select
 * \detail
 * 		0: DMA is disabled
 * 		1: DMA is enabled. When enabled, DMA request is generated by
 * 		   original interrupts. The interrupts will not be presented
 * 		   on this module at the same time
 */
#define C1_DMAEN\
	(0)

/**
 * \def		C1_DACBFMD
 * \brief	C1[2] which is DAC Buffer Work Mode Select
 * \detail
 * 		0: Normal mode
 * 		1: One-Time Scan mode
 */
#define C1_DACBFMD\
	(0)

/**
 * \def		C1_DACBFEN
 * \brief	C1[0] which is DAC Buffer Enable
 * \detail
 * 		0: Buffer read pointer is disabled. The converted data
 * 		   is always the first word of the buffer
 * 		1: Buffer read pointer is enabled. The converted data
 * 		   is the word that the read pointer points to. It means
 * 		   converted data can be from any word of the buffer
 */
#define C1_DACBFEN\
	(0)

/**
 * \def		C2_DACBFRP
 * \brief	C2[4] which is DAC Buffer Read Pointer
 * \detail
 * 		Keeps the current value of the buffer read pointer
 */
#define C2_DACBFRP\
	(0)

/**
 * \def		C2_DACBFUP
 * \brief	C2[0] which is DAC Buffer Upper Limit
 * \detail
 * 		Selects the upper limit of the DAC buffer.
 * 		The buffer read pointer cannot exceed it
 */
#define C2_DACBFUP\
	(0)

void init_onboard_dac(void)
{
	/**
     * Enable clock to Port E
     * Enable clock to DAC0
     */
	SIM->SCGC6 |= SIM_SCGC6_DAC0_MASK;
    SIM->SCGC5 |= SIM_SCGC5_PORTE_MASK;

    /**
     * Set PTE30 to Analog
     *
     * The MUX selection in PCR is done with bits 10:8, where 000 is configuration as Analog
     */
    PORTE->PCR[PORTE_DAC0_POS] &= ~PORT_PCR_MUX_MASK;
    PORTE->PCR[PORTE_DAC0_POS] |= PORT_PCR_MUX(PCR_MUX_SEL_DAC);

	/**
	 * Configure DAC0:
	 * 	- Disable DMA
	 * 	- Disable buffer
	 */
    DAC0->C1 =
    	DAC_C1_DMAEN(C1_DMAEN) |
		DAC_C1_DACBFMD(C1_DACBFMD) |
		DAC_C1_DACBFEN(C1_DACBFEN);
    DAC0->C2 =
    	DAC_C2_DACBFRP(C2_DACBFRP) |
		DAC_C2_DACBFUP(C2_DACBFUP);

	/**
	 * Configure DAC0:
	 * 	- Enable DAC
	 * 	- Select VDDA as reference voltage
	 */
    DAC0->C0 =
    	DAC_C0_DACEN(C0_DACEN) |
		DAC_C0_DACRFS(C0_DACRFS);
}
